In [73]:
import seaborn as sns
df=sns.load_dataset('tips')

In [74]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [76]:
df.shape

(244, 7)

In [77]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [78]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [79]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [80]:
x=df[['tip', 'sex', 'smoker', 'day', 'time']]
y=df['total_bill']

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [83]:
x_train.head()

      tip     sex smoker  day    time
115  3.50  Female     No  Sun  Dinner
181  5.65    Male    Yes  Sun  Dinner
225  2.50  Female    Yes  Fri   Lunch
68   2.01    Male     No  Sat  Dinner
104  4.08  Female     No  Sat  Dinner

In [84]:
from sklearn.preprocessing import LabelEncoder
encoder1=LabelEncoder()
encoder2=LabelEncoder()
encoder3=LabelEncoder()

In [85]:
x_train['sex']=encoder1.fit_transform(x_train['sex'])
x_train['smoker']=encoder2.fit_transform(x_train['smoker'])
x_train['time']=encoder3.fit_transform(x_train['time'])

In [87]:
x_test['sex']=encoder1.transform(x_test['sex'])
x_test['smoker']=encoder2.transform(x_test['smoker'])
x_test['time']=encoder3.transform(x_test['time'])

In [88]:
x_train.head()

      tip  sex  smoker  day  time
115  3.50    0       0  Sun     0
181  5.65    1       1  Sun     0
225  2.50    0       1  Fri     1
68   2.01    1       0  Sat     0
104  4.08    0       0  Sat     0

In [89]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [93]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],remainder='passthrough')

In [94]:
x_train['day']=ct.fit_transform(x_train['day'])

IndexError: tuple index out of range