In [1]:
import pandas as pd

In [2]:
df=pd.read_excel('flight_price.xlsx')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [3]:
df.shape

(10683, 11)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [5]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [6]:
df['Date']=df['Date_of_Journey'].str.split('/').str[0]
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01

In [7]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01

In [8]:
df['Month']=df['Date_of_Journey'].str.split('/').str[1]
df['Year']=df['Date_of_Journey'].str.split('/').str[2]
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03,2019

In [9]:

df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019

In [10]:
df['Date']=df['Date'].astype(int)
df['Month']=df['Month'].astype(int)
df['Year']=df['Year'].astype(int)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [12]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

In [13]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [14]:
df[df['Total_Stops'].isnull()]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
9039,Air India,6/05/2019,Delhi,Cochin,NaN,09:45,09:25 07 May,23h 40m,NaN,No info,7480,6,5,2019

In [15]:
import numpy as np

In [16]:
df['Total_Stops'] = df['Total_Stops'].str.strip().map({
    'non-stop': 0,
    '1 stop': 1,
    '2 stops': 2,
    '3 stops': 3,
    '4 stops': 4,
    np.nan:1
})

In [17]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,0,No info,3897,24,3,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2,No info,7662,1,5,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2,No info,13882,9,6,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1,No info,6218,12,5,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1,No info,13302,1,3,2019

In [18]:
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,0,No info,3897,24,3,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2,No info,7662,1,5,2019

In [19]:
df.drop(['Date_of_Journey'],inplace=True,axis=1)

In [20]:
df.drop(['Route','Additional_Info'],inplace=True,axis=1)

In [21]:
df.head(3)

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,0,3897,24,3,2019
1,Air India,Kolkata,Banglore,05:50,13:15,7h 25m,2,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,09:25,04:25 10 Jun,19h,2,13882,9,6,2019

In [22]:
df['Arrival_Time']=df['Arrival_Time'].apply(lambda x:x.split(' ')[0])

In [23]:
df['Arrival_hour']=df['Arrival_Time'].str.split(':').str[0]
df.head(4)

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price,Date,Month,Year,Arrival_hour
0,IndiGo,Banglore,New Delhi,22:20,01:10,2h 50m,0,3897,24,3,2019,01
1,Air India,Kolkata,Banglore,05:50,13:15,7h 25m,2,7662,1,5,2019,13
2,Jet Airways,Delhi,Cochin,09:25,04:25,19h,2,13882,9,6,2019,04
3,IndiGo,Kolkata,Banglore,18:05,23:30,5h 25m,1,6218,12,5,2019,23

In [24]:
df['Arrival_Mins']=df['Arrival_Time'].str.split(':').str[1]
df.head(2)

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_Mins
0,IndiGo,Banglore,New Delhi,22:20,01:10,2h 50m,0,3897,24,3,2019,01,10
1,Air India,Kolkata,Banglore,05:50,13:15,7h 25m,2,7662,1,5,2019,13,15

In [25]:
df.drop('Arrival_Time',inplace=True,axis=1)

In [26]:
df.head(2)

,Airline,Source,Destination,Dep_Time,Duration,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_Mins
0,IndiGo,Banglore,New Delhi,22:20,2h 50m,0,3897,24,3,2019,01,10
1,Air India,Kolkata,Banglore,05:50,7h 25m,2,7662,1,5,2019,13,15

In [27]:
df['Duration']

0        2h 50m
1        7h 25m
2           19h
3        5h 25m
4        4h 45m
          ...
10678    2h 30m
10679    2h 35m
10680        3h
10681    2h 40m
10682    8h 20m
Name: Duration, Length: 10683, dtype: object

In [28]:
df['Duration_Hour']=df['Duration'].str.extract(r'(\d+)h')

In [29]:
df.head(6475)

,Airline,Source,Destination,Dep_Time,Duration,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_Mins,Duration_Hour
0,IndiGo,Banglore,New Delhi,22:20,2h 50m,0,3897,24,3,2019,01,10,2
1,Air India,Kolkata,Banglore,05:50,7h 25m,2,7662,1,5,2019,13,15,7
2,Jet Airways,Delhi,Cochin,09:25,19h,2,13882,9,6,2019,04,25,19
3,IndiGo,Kolkata,Banglore,18:05,5h 25m,1,6218,12,5,2019,23,30,5
4,IndiGo,Banglore,New Delhi,16:50,4h 45m,1,13302,1,3,2019,21,35,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6470,Multiple carriers Premium economy,Delhi,Cochin,08:55,12h 5m,1,9845,21,3,2019,21,00,12
6471,IndiGo,Banglore,Delhi,01:30,2h 45m,0,4077,1,5,2019,04,15,2
6472,Multiple carriers,Delhi,Cochin,07:30,11h 30m,1,9315,21,5,2019,19,00,11
6473,Jet Airways,Kolkata,Banglore,14:05,9h 30m,1,14781,9,5,2019,23,35,9
6474,Air India,Mumbai,Hyderabad,16:50,5m,2,17327,6,3,2019,16,55,NaN

In [30]:
df['Duration_Hour']=df['Duration_Hour'].fillna(0)

In [31]:
df.head(6476)

,Airline,Source,Destination,Dep_Time,Duration,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_Mins,Duration_Hour
0,IndiGo,Banglore,New Delhi,22:20,2h 50m,0,3897,24,3,2019,01,10,2
1,Air India,Kolkata,Banglore,05:50,7h 25m,2,7662,1,5,2019,13,15,7
2,Jet Airways,Delhi,Cochin,09:25,19h,2,13882,9,6,2019,04,25,19
3,IndiGo,Kolkata,Banglore,18:05,5h 25m,1,6218,12,5,2019,23,30,5
4,IndiGo,Banglore,New Delhi,16:50,4h 45m,1,13302,1,3,2019,21,35,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6471,IndiGo,Banglore,Delhi,01:30,2h 45m,0,4077,1,5,2019,04,15,2
6472,Multiple carriers,Delhi,Cochin,07:30,11h 30m,1,9315,21,5,2019,19,00,11
6473,Jet Airways,Kolkata,Banglore,14:05,9h 30m,1,14781,9,5,2019,23,35,9
6474,Air India,Mumbai,Hyderabad,16:50,5m,2,17327,6,3,2019,16,55,0
6475,Air India,Banglore,New Delhi,17:00,2h 50m,0,9481,9,3,2019,19,50,2

In [32]:
df['Duration_Mins']=df['Duration'].str.extract(r'(\d+)m')
df.head(6476)

,Airline,Source,Destination,Dep_Time,Duration,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_Mins,Duration_Hour,Duration_Mins
0,IndiGo,Banglore,New Delhi,22:20,2h 50m,0,3897,24,3,2019,01,10,2,50
1,Air India,Kolkata,Banglore,05:50,7h 25m,2,7662,1,5,2019,13,15,7,25
2,Jet Airways,Delhi,Cochin,09:25,19h,2,13882,9,6,2019,04,25,19,NaN
3,IndiGo,Kolkata,Banglore,18:05,5h 25m,1,6218,12,5,2019,23,30,5,25
4,IndiGo,Banglore,New Delhi,16:50,4h 45m,1,13302,1,3,2019,21,35,4,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6471,IndiGo,Banglore,Delhi,01:30,2h 45m,0,4077,1,5,2019,04,15,2,45
6472,Multiple carriers,Delhi,Cochin,07:30,11h 30m,1,9315,21,5,2019,19,00,11,30
6473,Jet Airways,Kolkata,Banglore,14:05,9h 30m,1,14781,9,5,2019,23,35,9,30
6474,Air India,Mumbai,Hyderabad,16:50,5m,2,17327,6,3,2019,16,55,0,5
6475,Air India,Banglore,New Delhi,17:00,2h 50m,0,9481,9,3,2019,19,50,2,50

In [33]:
df['Duration_Mins']=df['Duration_Mins'].fillna(0)

In [34]:
df['Duration_Mins'].isnull().sum()

np.int64(0)

In [35]:
df['Duration_Hour']=df['Duration_Hour'].astype(int)

df['Duration_Mins']=df['Duration_Mins'].astype(int)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Airline        10683 non-null  object
 1   Source         10683 non-null  object
 2   Destination    10683 non-null  object
 3   Dep_Time       10683 non-null  object
 4   Duration       10683 non-null  object
 5   Total_Stops    10683 non-null  int64
 6   Price          10683 non-null  int64
 7   Date           10683 non-null  int64
 8   Month          10683 non-null  int64
 9   Year           10683 non-null  int64
 10  Arrival_hour   10683 non-null  object
 11  Arrival_Mins   10683 non-null  object
 12  Duration_Hour  10683 non-null  int64
 13  Duration_Mins  10683 non-null  int64
dtypes: int64(7), object(7)
memory usage: 1.1+ MB

In [37]:
df['Arrival_hour']=df['Arrival_hour'].astype(int)
df['Arrival_Mins']=df['Arrival_Mins'].astype(int)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Airline        10683 non-null  object
 1   Source         10683 non-null  object
 2   Destination    10683 non-null  object
 3   Dep_Time       10683 non-null  object
 4   Duration       10683 non-null  object
 5   Total_Stops    10683 non-null  int64
 6   Price          10683 non-null  int64
 7   Date           10683 non-null  int64
 8   Month          10683 non-null  int64
 9   Year           10683 non-null  int64
 10  Arrival_hour   10683 non-null  int64
 11  Arrival_Mins   10683 non-null  int64
 12  Duration_Hour  10683 non-null  int64
 13  Duration_Mins  10683 non-null  int64
dtypes: int64(9), object(5)
memory usage: 1.1+ MB

In [39]:
df.head()

,Airline,Source,Destination,Dep_Time,Duration,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_Mins,Duration_Hour,Duration_Mins
0,IndiGo,Banglore,New Delhi,22:20,2h 50m,0,3897,24,3,2019,1,10,2,50
1,Air India,Kolkata,Banglore,05:50,7h 25m,2,7662,1,5,2019,13,15,7,25
2,Jet Airways,Delhi,Cochin,09:25,19h,2,13882,9,6,2019,4,25,19,0
3,IndiGo,Kolkata,Banglore,18:05,5h 25m,1,6218,12,5,2019,23,30,5,25
4,IndiGo,Banglore,New Delhi,16:50,4h 45m,1,13302,1,3,2019,21,35,4,45

In [40]:
df['Dep_hour']=df['Dep_Time'].str.split(':').str[0]
df['Dep_Min']=df['Dep_Time'].str.split(':').str[1]

In [41]:
df.head(3)

,Airline,Source,Destination,Dep_Time,Duration,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_Mins,Duration_Hour,Duration_Mins,Dep_hour,Dep_Min
0,IndiGo,Banglore,New Delhi,22:20,2h 50m,0,3897,24,3,2019,1,10,2,50,22,20
1,Air India,Kolkata,Banglore,05:50,7h 25m,2,7662,1,5,2019,13,15,7,25,05,50
2,Jet Airways,Delhi,Cochin,09:25,19h,2,13882,9,6,2019,4,25,19,0,09,25

In [42]:
df['Dep_hour']=df['Dep_hour'].astype(int)
df['Dep_Min']=df['Dep_Min'].astype(int)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Airline        10683 non-null  object
 1   Source         10683 non-null  object
 2   Destination    10683 non-null  object
 3   Dep_Time       10683 non-null  object
 4   Duration       10683 non-null  object
 5   Total_Stops    10683 non-null  int64
 6   Price          10683 non-null  int64
 7   Date           10683 non-null  int64
 8   Month          10683 non-null  int64
 9   Year           10683 non-null  int64
 10  Arrival_hour   10683 non-null  int64
 11  Arrival_Mins   10683 non-null  int64
 12  Duration_Hour  10683 non-null  int64
 13  Duration_Mins  10683 non-null  int64
 14  Dep_hour       10683 non-null  int64
 15  Dep_Min        10683 non-null  int64
dtypes: int64(11), object(5)
memory usage: 1.3+ MB

In [44]:
df.drop(['Dep_Time'],inplace=True,axis=1)

In [45]:
df.head(2)

,Airline,Source,Destination,Duration,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_Mins,Duration_Hour,Duration_Mins,Dep_hour,Dep_Min
0,IndiGo,Banglore,New Delhi,2h 50m,0,3897,24,3,2019,1,10,2,50,22,20
1,Air India,Kolkata,Banglore,7h 25m,2,7662,1,5,2019,13,15,7,25,5,50

In [46]:
df['Airline'].nunique()

12

SInce it has 12 unique values so we cant be using ordinal or lets say rank based ecoding so we are using one hot encoding (sparse matrix technique)

In [47]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [48]:
encoder=OneHotEncoder()

In [49]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_Mins,Duration_Hour,Duration_Mins,Dep_hour,Dep_Min
0,IndiGo,Banglore,New Delhi,2h 50m,0,3897,24,3,2019,1,10,2,50,22,20
1,Air India,Kolkata,Banglore,7h 25m,2,7662,1,5,2019,13,15,7,25,5,50
2,Jet Airways,Delhi,Cochin,19h,2,13882,9,6,2019,4,25,19,0,9,25
3,IndiGo,Kolkata,Banglore,5h 25m,1,6218,12,5,2019,23,30,5,25,18,5
4,IndiGo,Banglore,New Delhi,4h 45m,1,13302,1,3,2019,21,35,4,45,16,50

One important lesson I learned is that we need to separetely create dataframe for these categorical values like Airline ,Source and destination && merge it with the original eda cleaned dataset.I did mistake here by converting these data frame together so its a message to all of us to not repeat such mistake again.